// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGjTvFkKZda7qDh1TTrqPwPkgYC76_b7E',
    appId: '1:75814891396:android:a5502330afc0a20a2737d1',
    messagingSenderId: '75814891396',
    projectId: 'expense-tracker-455519',
    storageBucket: 'expense-tracker-455519.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADmQSOOg7oKYh4MBa7WNOyRGxs4OlxjmY',
    appId: '1:75814891396:ios:23e273bfdea805362737d1',
    messagingSenderId: '75814891396',
    projectId: 'expense-tracker-455519',
    storageBucket: 'expense-tracker-455519.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADmQSOOg7oKYh4MBa7WNOyRGxs4OlxjmY',
    appId: '1:75814891396:ios:23e273bfdea805362737d1',
    messagingSenderId: '75814891396',
    projectId: 'expense-tracker-455519',
    storageBucket: 'expense-tracker-455519.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWdZOjqGiSjUrmgulTODivWLq-Xmh3lw0',
    appId: '1:75814891396:web:a0fd3f3e5892b86a2737d1',
    messagingSenderId: '75814891396',
    projectId: 'expense-tracker-455519',
    authDomain: 'expense-tracker-455519.firebaseapp.com',
    storageBucket: 'expense-tracker-455519.firebasestorage.app',
  );

}