// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV3fp8TNpmrZNAdbtS_iq1CvPUrTMs4uQ',
    appId: '1:754618202147:android:207f2bc6bf2d24f7d55996',
    messagingSenderId: '754618202147',
    projectId: 'vital-range-448621-q8',
    storageBucket: 'vital-range-448621-q8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUVk3k7s83vCVMhbzOsynJEE3gMCRfKUs',
    appId: '1:754618202147:ios:9b77825a8ba6a2f7d55996',
    messagingSenderId: '754618202147',
    projectId: 'vital-range-448621-q8',
    storageBucket: 'vital-range-448621-q8.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUVk3k7s83vCVMhbzOsynJEE3gMCRfKUs',
    appId: '1:754618202147:ios:9b77825a8ba6a2f7d55996',
    messagingSenderId: '754618202147',
    projectId: 'vital-range-448621-q8',
    storageBucket: 'vital-range-448621-q8.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Wfj60XsesAKBGTYyYrEvFUdgalxT0vA',
    appId: '1:754618202147:web:488c208ef38be2c2d55996',
    messagingSenderId: '754618202147',
    projectId: 'vital-range-448621-q8',
    authDomain: 'vital-range-448621-q8.firebaseapp.com',
    storageBucket: 'vital-range-448621-q8.firebasestorage.app',
  );

}